MAX_STEPS_IN_SIMULATION = 300

PORTION_OF_POPULATION_EXPOSED = 0.5
PORTION_OF_POPULATION_INFECTED = 0.2
BETA_KEEP_LOCAL_STATE_FRACTION = 0.5


# omega = 0
SEIR_RATE_RECOVERY = 0
SEIR_RATE_NATURAL_DEATH = 0     # mu
SEIR_RATE_NATURAL_BIRTH = 0     # nu

# h = 0.1
SEIR_TIME_STEP = 0.5

# Influenza
SEIR_PERIOD_LATENT = 1 / 1.2                # sigma
SEIR_INFECTED_PERIOD = 1 / 1.2              # gamma
SEIR_TRANSMISSION_COEFFICIENT = 1 / 1.66    # beta


# TUBERCULOSIS
SEIR_PERIOD_LATENT = 0.000310               # sigma
SEIR_INFECTED_PERIOD = 0.123111             # gamma
SEIR_TRANSMISSION_COEFFICIENT = 0.326655    # beta


# Smallpox
SEIR_PERIOD_LATENT = 3                      # sigma
SEIR_INFECTED_PERIOD = 19/60                # gamma
SEIR_TRANSMISSION_COEFFICIENT = 6/5         # beta
